namespace PDT.Plugins.Marantz
{
    public enum SurroundModes
    {
        Unknown,
        Direct,
        PureDirect,
        Stereo,
        Standard,
        DolbyDigital,
        DTS,
        MultiChannelStereo,
        MultiChannelIn,
        MultiChannelDSurround,
        RockArena,
        JazzClub,
        MonoMovie,
        Matrix,
        VideoGame,
        Virtual,
        Auto,
        Neural,
        Auro3D,
        Auro2DSurround,
        Left,
        Right,
        Movie,
        Music,
        Game,
    }
}
